apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: deploymenttest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deploymenttest 
    spec:
      containers:
        - name: deploymenttest 
          image: deploytest.azurecr.io/deploymenttest
          ports:
          - containerPort: 8080