apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: hwkdeploymenttest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hwkdeploymenttest 
    spec:
      containers:
        - name: hwkdeploymenttest 
          image: deploytest.azurecr.io/hwkdeploymenttest
          ports:
          - containerPort: 8080